import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

const commonPackages = {
  name: "",
  version: "0.1.0",
  private: true,
  scripts: {
    dev: "next dev",
    build: "next build",
    start: "next start",
    lint: "eslint .",
    typecheck: "tsc --noEmit",
  },
  dependencies: {
    next: "15.2.4",
    react: "19.0.0",
    "react-dom": "19.0.0",
  },
  devDependencies: {
    "@types/node": "^22.13.10",
    "@types/react": "^19.0.10",
    "@types/react-dom": "^19.0.4",
    autoprefixer: "^10.4.21",
    eslint: "^9.22.0",
    "eslint-config-next": "15.2.4",
    postcss: "^8.5.3",
    tailwindcss: "^3.4.17",
    typescript: "^5.8.2",
  },
};

const commonFiles = {
  ".gitignore": `node_modules
.next
out
coverage
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.env
.env.local
.env.production.local
.env.development.local
.DS_Store
dist
`,
  ".env.example": `NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_APP_NAME=
`,
  "next-env.d.ts": `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js.
`,
  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`,
  "postcss.config.mjs": `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "rgb(var(--surface) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
      },
      boxShadow: {
        soft: "0 20px 80px rgba(15, 23, 42, 0.16)",
      },
      backgroundImage: {
        grid: "linear-gradient(to right, rgba(148,163,184,0.12) 1px, transparent 1px), linear-gradient(to bottom, rgba(148,163,184,0.12) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};

export default config;
`,
  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
  "eslint.config.mjs": `import nextVitals from "eslint-config-next/core-web-vitals";

export default [...nextVitals];
`,
  "app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: 248 250 252;
  --foreground: 15 23 42;
  --surface: 255 255 255;
  --surface-muted: 241 245 249;
  --border: 203 213 225;
  --primary: 14 116 144;
  --secondary: 245 158 11;
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  min-height: 100vh;
  color: rgb(var(--foreground));
  background:
    radial-gradient(circle at top left, rgba(var(--secondary), 0.18), transparent 28%),
    radial-gradient(circle at top right, rgba(var(--primary), 0.14), transparent 32%),
    linear-gradient(180deg, rgba(248, 250, 252, 1) 0%, rgba(241, 245, 249, 1) 100%);
}

a {
  color: inherit;
  text-decoration: none;
}

.section-shell {
  @apply mx-auto max-w-7xl px-6 lg:px-8;
}

.panel {
  @apply rounded-3xl border border-slate-200/80 bg-white/85 shadow-soft backdrop-blur;
}

.pill {
  @apply inline-flex items-center rounded-full border border-slate-300 bg-white/80 px-4 py-1 text-sm font-medium text-slate-600;
}

.grid-pattern {
  background-size: 28px 28px;
}
`,
  "components/site-header.tsx": `import Link from "next/link";
import { siteConfig } from "@/lib/site";

export function SiteHeader() {
  return (
    <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/75 backdrop-blur">
      <div className="section-shell flex h-16 items-center justify-between">
        <Link href="/" className="flex items-center gap-3">
          <span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-sm font-semibold text-primary">
            {siteConfig.brandMark}
          </span>
          <div>
            <p className="font-semibold text-slate-950">{siteConfig.name}</p>
            <p className="text-xs text-slate-500">{siteConfig.tagline}</p>
          </div>
        </Link>
        <nav className="hidden items-center gap-6 text-sm font-medium text-slate-600 md:flex">
          {siteConfig.mainNav.map((item) => (
            <Link key={item.href} href={item.href} className="transition hover:text-slate-950">
              {item.label}
            </Link>
          ))}
        </nav>
        <Link
          href={siteConfig.cta.href}
          className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800"
        >
          {siteConfig.cta.label}
        </Link>
      </div>
    </header>
  );
}
`,
  "components/site-footer.tsx": `import Link from "next/link";
import { siteConfig } from "@/lib/site";

export function SiteFooter() {
  return (
    <footer className="border-t border-slate-200/80 bg-white/80">
      <div className="section-shell flex flex-col gap-6 py-10 md:flex-row md:items-center md:justify-between">
        <div>
          <p className="font-semibold text-slate-950">{siteConfig.name}</p>
          <p className="mt-2 max-w-xl text-sm text-slate-600">{siteConfig.footer}</p>
        </div>
        <div className="flex flex-wrap gap-4 text-sm text-slate-600">
          {siteConfig.mainNav.map((item) => (
            <Link key={item.href} href={item.href} className="transition hover:text-slate-950">
              {item.label}
            </Link>
          ))}
        </div>
      </div>
    </footer>
  );
}
`,
  "components/page-hero.tsx": `type PageHeroProps = {
  eyebrow: string;
  title: string;
  description: string;
};

export function PageHero({ eyebrow, title, description }: PageHeroProps) {
  return (
    <section className="section-shell py-16">
      <div className="panel overflow-hidden">
        <div className="grid-pattern bg-grid px-8 py-14 lg:px-14">
          <span className="pill">{eyebrow}</span>
          <h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-tight text-slate-950 lg:text-5xl">
            {title}
          </h1>
          <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">{description}</p>
        </div>
      </div>
    </section>
  );
}
`,
  "components/content-grid.tsx": `import Link from "next/link";

type ContentItem = {
  title: string;
  description: string;
  href?: string;
  meta?: string;
};

type ContentGridProps = {
  items: ContentItem[];
};

export function ContentGrid({ items }: ContentGridProps) {
  return (
    <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
      {items.map((item) => (
        <article key={item.title} className="panel p-6">
          {item.meta ? <p className="text-sm font-medium text-primary">{item.meta}</p> : null}
          <h3 className="mt-3 text-xl font-semibold text-slate-950">{item.title}</h3>
          <p className="mt-3 text-sm leading-7 text-slate-600">{item.description}</p>
          {item.href ? (
            <Link href={item.href} className="mt-5 inline-flex text-sm font-semibold text-slate-950">
              Explore
            </Link>
          ) : null}
        </article>
      ))}
    </div>
  );
}
`,
  "components/contact-form.tsx": `type ContactFormProps = {
  submitLabel: string;
  context: string;
};

export function ContactForm({ submitLabel, context }: ContactFormProps) {
  return (
    <form className="panel p-8">
      <div className="grid gap-5 md:grid-cols-2">
        <label className="text-sm font-medium text-slate-700">
          Name
          <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm" placeholder="Your name" />
        </label>
        <label className="text-sm font-medium text-slate-700">
          Email
          <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm" placeholder="you@company.com" />
        </label>
      </div>
      <label className="mt-5 block text-sm font-medium text-slate-700">
        Company
        <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm" placeholder="Company name" />
      </label>
      <label className="mt-5 block text-sm font-medium text-slate-700">
        Project context
        <textarea
          rows={6}
          defaultValue={context}
          className="mt-2 w-full rounded-3xl border border-slate-200 bg-white px-4 py-3 text-sm"
        />
      </label>
      <button
        type="submit"
        className="mt-6 inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
      >
        {submitLabel}
      </button>
    </form>
  );
}
`,
  "components/app-shell.tsx": `import Link from "next/link";

type AppShellProps = {
  title: string;
  description: string;
  nav: { label: string; href: string }[];
  children: React.ReactNode;
};

export function AppShell({ title, description, nav, children }: AppShellProps) {
  return (
    <div className="section-shell py-16">
      <div className="grid gap-8 lg:grid-cols-[260px_1fr]">
        <aside className="panel p-6">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Workspace</p>
          <h1 className="mt-3 text-2xl font-semibold text-slate-950">{title}</h1>
          <p className="mt-3 text-sm leading-7 text-slate-600">{description}</p>
          <nav className="mt-8 flex flex-col gap-3">
            {nav.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700 transition hover:border-slate-950 hover:text-slate-950"
              >
                {item.label}
              </Link>
            ))}
          </nav>
        </aside>
        <div className="space-y-6">{children}</div>
      </div>
    </div>
  );
}
`,
  "app/layout.tsx": `import type { Metadata } from "next";
import { Manrope, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { siteConfig } from "@/lib/site";

const sans = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
});

const display = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description,
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={\`\${sans.variable} \${display.variable} font-[family-name:var(--font-sans)] text-slate-950 antialiased\`}>
        <div className="relative flex min-h-screen flex-col">
          <SiteHeader />
          <main className="flex-1">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
`,
  ".github/workflows/ci.yml": `name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
`,
  ".github/workflows/deploy.yml": `name: Deploy Placeholder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Configure deployment steps for your hosting provider."
`,
  "public/.gitkeep": ``,
};

const projects = [
  {
    slug: "cloud-nexus-pilot",
    name: "Cloud Nexus Pilot",
    brandMark: "CNP",
    tagline: "AI interview and meeting copilot",
    description: "A polished SaaS starter for interview prep, transcript uploads, prompt libraries, and AI-generated debriefs.",
    footer: "Built to help operators and candidates turn raw conversations into useful next actions.",
    cta: { label: "Open Dashboard", href: "/dashboard" },
    mainNav: [
      { label: "Pricing", href: "/pricing" },
      { label: "Prompt Library", href: "/prompt-library" },
      { label: "Transcripts", href: "/transcripts" },
      { label: "Login", href: "/auth/login" },
    ],
    home: {
      eyebrow: "Interview Intelligence",
      title: "Turn every interview and meeting into a clear action plan.",
      description: "Cloud Nexus Pilot helps teams upload transcripts, centralize prompts, and route every conversation into a structured AI workflow.",
      stats: [
        { title: "Transcript ready", description: "Fast upload flow designed for recruiter screens, coaching sessions, and team meetings.", meta: "01" },
        { title: "Prompt governance", description: "Store reusable prompt sets for summaries, interview scorecards, and follow-up generation.", meta: "02" },
        { title: "Operator dashboard", description: "Start with a dashboard shell that is ready for analytics, billing, and workspace settings.", meta: "03" },
      ],
      highlights: [
        { title: "Upload once, summarize later", description: "Prepare a transcript pipeline with room for ASR ingestion, storage, and review queues." },
        { title: "SaaS-grade information architecture", description: "Marketing, auth, and app surfaces are separated so the product can scale cleanly." },
        { title: "Ready for future integrations", description: "Docs capture follow-up work for auth providers, storage backends, and model orchestration." },
      ],
    },
    pages: {
      pricing: {
        eyebrow: "Pricing",
        title: "Simple plans for solo operators and scaling teams.",
        description: "Start with clear packages and leave room for usage-based AI billing later.",
        items: [
          { title: "Starter", description: "Landing pages, prompt storage patterns, transcript upload placeholders, and one workspace.", meta: "$29/mo" },
          { title: "Pro", description: "Team-level prompt governance, richer dashboards, and admin review workflows.", meta: "$99/mo" },
          { title: "Enterprise", description: "Private deployment, advanced audit controls, and tailored onboarding.", meta: "Custom" },
        ],
      },
      promptLibrary: {
        eyebrow: "Prompt Library",
        title: "Centralize prompts for every call workflow.",
        description: "Collect battle-tested prompts for summaries, scorecards, stakeholder updates, and coaching follow-ups.",
        items: [
          { title: "Interview Debrief", description: "Generate strengths, risks, and recommended follow-up questions in one pass." },
          { title: "Meeting Summary", description: "Turn a long transcript into a crisp recap with owners, decisions, and blockers." },
          { title: "Candidate Scorecard", description: "Map transcript evidence against role competencies and expected behaviors." },
        ],
      },
    },
    tasks: [
      "Connect a real auth provider such as Clerk, Auth0, or Supabase Auth.",
      "Choose transcript storage and file upload infrastructure.",
      "Select the production AI workflow for summaries, redaction, and prompt versioning.",
    ],
  },
  {
    slug: "devops-automation-agency",
    name: "DevOps Automation Agency",
    brandMark: "DAA",
    tagline: "AWS, cloud security, and platform automation consulting",
    description: "A modern agency site for pipeline acceleration, infrastructure modernization, cloud security hardening, and advisory engagements.",
    footer: "Positioned for consulting leads, case studies, service packaging, and outbound conversion.",
    cta: { label: "Book Discovery", href: "/lead-form" },
    mainNav: [
      { label: "Services", href: "/services" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "Contact", href: "/contact" },
      { label: "Lead Form", href: "/lead-form" },
    ],
    home: {
      eyebrow: "Cloud Delivery Systems",
      title: "Ship infrastructure faster without trading away reliability.",
      description: "DevOps Automation Agency packages cloud architecture, automation engineering, and security posture uplift into clean service lines.",
      stats: [
        { title: "AWS modernization", description: "Migration plans, landing zones, observability, and resilient delivery pipelines.", meta: "01" },
        { title: "Security-first automation", description: "Guardrails, IAM cleanup, secrets handling, and repeatable compliance workflows.", meta: "02" },
        { title: "Clear consulting funnels", description: "Lead capture and discovery flows built for advisory services.", meta: "03" },
      ],
      highlights: [
        { title: "Offer clarity", description: "Service packaging separates retained platform work from fixed-scope automation projects." },
        { title: "Sales-ready content", description: "Case study and booking pages help this repo function like a launchable agency site." },
        { title: "Low-friction expansion", description: "The structure is ready for CMS wiring, CRM forms, and analytics instrumentation." },
      ],
    },
    pages: {
      services: {
        eyebrow: "Services",
        title: "Consulting offers that move infrastructure teams forward.",
        description: "Frame the engagement menu around architecture, security, and automation outcomes.",
        items: [
          { title: "Platform Acceleration", description: "CI/CD modernization, release automation, and developer platform improvements." },
          { title: "AWS Security Hardening", description: "IAM redesign, guardrails, logging posture, and incident readiness." },
          { title: "Cloud Cost and Reliability Reviews", description: "Performance tuning, backup validation, and architecture recommendations." },
        ],
      },
      caseStudies: {
        eyebrow: "Case Studies",
        title: "Proof points for executive buyers and engineering leaders.",
        description: "Use these placeholders for anonymized delivery wins and transformation stories.",
        items: [
          { title: "Pipeline Lead Time Reduction", description: "Document a before-and-after delivery workflow for a scaling product team." },
          { title: "Landing Zone Security Retrofit", description: "Show how baseline controls improved audit readiness and access hygiene." },
          { title: "Runbook Automation Rollout", description: "Explain how scripted operations reduced support burden and MTTR." },
        ],
      },
    },
    tasks: [
      "Connect the lead and contact forms to your CRM or inbox automation.",
      "Replace placeholder case studies with approved client stories and metrics.",
      "Decide on a booking provider such as Cal.com, Calendly, or a custom scheduling flow.",
    ],
  },
  {
    slug: "cloud-security-digital-factory",
    name: "Cloud Security Digital Factory",
    brandMark: "CDF",
    tagline: "Digital storefront for templates, SOPs, and cloud playbooks",
    description: "A storefront-focused Next.js foundation for digital products like Terraform modules, security SOPs, and documentation kits.",
    footer: "Designed for packaged expertise, downloadable assets, and future gated delivery flows.",
    cta: { label: "Browse Catalog", href: "/catalog" },
    mainNav: [
      { label: "Catalog", href: "/catalog" },
      { label: "Pricing", href: "/pricing" },
      { label: "Downloads", href: "/downloads" },
      { label: "Contact", href: "/contact" },
    ],
    home: {
      eyebrow: "Digital Products",
      title: "Package cloud security knowledge into products people can buy today.",
      description: "Cloud Security Digital Factory is built for templates, bundles, and reusable operational assets across security and platform teams.",
      stats: [
        { title: "Catalog-first UX", description: "Merchandise Terraform assets, SOP bundles, and advisory documentation with confidence.", meta: "01" },
        { title: "Bundle-ready pricing", description: "Support single products, curated collections, and future membership packaging.", meta: "02" },
        { title: "Download delivery path", description: "Reserve space for gated assets, receipts, and customer file access.", meta: "03" },
      ],
      highlights: [
        { title: "Frictionless merchandising", description: "Product and pricing pages are shaped for digital inventory from day one." },
        { title: "Operational credibility", description: "The language and structure fit serious security artifacts rather than generic ebook templates." },
        { title: "Future commerce hooks", description: "This repo is ready for Stripe, Lemon Squeezy, or custom delivery workflows later." },
      ],
    },
    products: [
      { slug: "terraform-landing-zone-kit", name: "Terraform Landing Zone Kit", summary: "A modular AWS baseline with guardrails, networking, and account patterns.", price: "$149", format: "Terraform + Docs" },
      { slug: "incident-response-sop-bundle", name: "Incident Response SOP Bundle", summary: "Response playbooks, comms templates, and escalation checklists for cloud incidents.", price: "$89", format: "Docs Bundle" },
      { slug: "cloud-security-documentation-pack", name: "Cloud Security Documentation Pack", summary: "Policies, architecture review templates, and evidence collection worksheets.", price: "$129", format: "Documentation Kit" },
    ],
    pages: {
      pricing: {
        eyebrow: "Bundles",
        title: "Flexible pricing for solo operators, teams, and repeat buyers.",
        description: "Offer products individually or package them into themed collections.",
        items: [
          { title: "Single Asset", description: "One focused digital product with documentation and implementation notes.", meta: "$49-$149" },
          { title: "Operator Bundle", description: "Bundle two to three related assets for a discounted starter pack.", meta: "$199" },
          { title: "Team Vault", description: "Multi-seat access and prioritized updates for internal platform teams.", meta: "$499" },
        ],
      },
    },
    tasks: [
      "Choose a payments and digital delivery platform.",
      "Add real product media, samples, and license terms.",
      "Define the post-purchase delivery mechanism for downloads and updates.",
    ],
  },
  {
    slug: "ai-automation-agency",
    name: "AI Automation Agency",
    brandMark: "AAA",
    tagline: "Workflow automation and AI operations services",
    description: "An agency-ready site for workflow design, AI operations, and business automation engagements across ops-heavy teams.",
    footer: "Shaped for lead generation, qualification, and proposal requests around AI-enabled service delivery.",
    cta: { label: "Request Proposal", href: "/proposal-request" },
    mainNav: [
      { label: "Offers", href: "/offers" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "Intake", href: "/intake" },
      { label: "Contact", href: "/contact" },
    ],
    home: {
      eyebrow: "Automation Systems",
      title: "Design workflow automation that gives your team leverage, not chaos.",
      description: "AI Automation Agency packages process mapping, orchestration, and human-in-the-loop delivery for modern service businesses.",
      stats: [
        { title: "Process-first scoping", description: "Map messy handoffs and repetitive tasks into clear automation opportunities.", meta: "01" },
        { title: "Proposal-ready funnel", description: "Qualification pages are tuned for serious buyers, not generic contact traffic.", meta: "02" },
        { title: "Case-study storytelling", description: "Present measured outcomes across revenue operations, support, and internal workflows.", meta: "03" },
      ],
      highlights: [
        { title: "High-signal agency UX", description: "Pages focus on outcomes, scoping, and conversion rather than buzzwords alone." },
        { title: "Expansion-friendly structure", description: "The app router setup leaves space for CMS content, proposals, and gated assets." },
        { title: "Clear next actions", description: "Offer, intake, and proposal pages are already laid out for lead progression." },
      ],
    },
    pages: {
      offers: {
        eyebrow: "Offers",
        title: "Service packages for practical AI and workflow automation.",
        description: "Lead with implementation offers that solve bottlenecks and create measurable throughput gains.",
        items: [
          { title: "Workflow Mapping Sprint", description: "Analyze current operations and produce a prioritized automation roadmap." },
          { title: "AI Ops Retainer", description: "Ongoing monitoring, prompt tuning, exception handling, and iteration support." },
          { title: "Back-Office Automation Build", description: "Deploy integrated workflows across intake, fulfillment, reporting, and QA." },
        ],
      },
      caseStudies: {
        eyebrow: "Case Studies",
        title: "Show how automation changes the economics of service delivery.",
        description: "Use these story slots for real examples once client approvals are ready.",
        items: [
          { title: "Client Onboarding Compression", description: "Demonstrate how onboarding steps moved from inbox chaos to workflow orchestration." },
          { title: "Support Queue Deflection", description: "Show how AI triage reduced repetitive support effort and improved response speed." },
          { title: "Proposal Assembly Automation", description: "Explain how internal quoting and proposal workflows were shortened dramatically." },
        ],
      },
    },
    tasks: [
      "Select your CRM and proposal generation toolchain.",
      "Connect intake and proposal forms to your automation backend.",
      "Replace placeholder case studies with approved customer stories and proof metrics.",
    ],
  },
  {
    slug: "cloud-nexus-market",
    name: "Cloud Nexus Market",
    brandMark: "CNM",
    tagline: "Ecommerce for cloud tools and digital products",
    description: "A commerce-first storefront for cloud assets, digital bundles, and future downloadable product fulfillment.",
    footer: "Built to merchandize categories, product inventory, and digital delivery in a clean market-style layout.",
    cta: { label: "Browse Products", href: "/products" },
    mainNav: [
      { label: "Categories", href: "/categories" },
      { label: "Products", href: "/products" },
      { label: "Downloads", href: "/downloads" },
      { label: "Contact", href: "/contact" },
    ],
    home: {
      eyebrow: "Cloud Commerce",
      title: "Launch a polished storefront for cloud operators and digital buyers.",
      description: "Cloud Nexus Market provides the structure for categories, listings, product details, and post-purchase digital downloads.",
      stats: [
        { title: "Merchandising pages", description: "Homepage and category flows designed to surface product collections cleanly.", meta: "01" },
        { title: "Product detail templates", description: "Each detail page is ready for richer media, checkout hooks, and reviews.", meta: "02" },
        { title: "Digital delivery path", description: "Reserve a downloads area for customer files and future order history.", meta: "03" },
      ],
      highlights: [
        { title: "Commerce without clutter", description: "The layout keeps the storefront crisp while leaving room for future checkout wiring." },
        { title: "Flexible category model", description: "You can extend into templates, audits, training kits, or implementation add-ons." },
        { title: "Ready for integrations", description: "The repo can grow into Stripe, Shopify headless, or custom cart workflows later." },
      ],
    },
    categories: [
      { title: "Terraform Kits", description: "Reusable infrastructure baselines and deployment templates." },
      { title: "Security Playbooks", description: "Runbooks, SOPs, and response guidance for cloud teams." },
      { title: "Documentation Packs", description: "Starter policies, architecture docs, and onboarding assets." },
    ],
    products: [
      { slug: "aws-observability-starter", name: "AWS Observability Starter", summary: "Dashboards, alarms, and documentation to speed up visibility across workloads.", price: "$79", format: "Template Pack" },
      { slug: "platform-runbook-vault", name: "Platform Runbook Vault", summary: "A curated set of operator runbooks for incident response, maintenance, and handoffs.", price: "$119", format: "Runbook Bundle" },
      { slug: "security-review-toolkit", name: "Security Review Toolkit", summary: "Checklists, architecture review sheets, and reporting templates for cloud security assessments.", price: "$99", format: "Toolkit" },
    ],
    tasks: [
      "Pick a commerce backend or checkout provider.",
      "Connect product inventory to a CMS, database, or external catalog.",
      "Define authenticated delivery for digital downloads and order history.",
    ],
  },
];

function mkdir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFile(projectRoot, relativePath, content) {
  const filePath = path.join(projectRoot, relativePath);
  mkdir(filePath);
  fs.writeFileSync(filePath, content);
}

function toTsExport(config) {
  return `export const siteConfig = ${JSON.stringify(config, null, 2)} as const;\n`;
}

function packageJson(project) {
  const pkg = structuredClone(commonPackages);
  pkg.name = project.slug;
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function readme(project) {
  return `# ${project.name}

${project.description}

## Stack

- Next.js with App Router
- TypeScript
- Tailwind CSS
- GitHub Actions placeholders for CI and deployment

## Getting Started

1. Install dependencies with \`npm install\`
2. Copy \`.env.example\` to \`.env.local\`
3. Start the dev server with \`npm run dev\`

## Included Pages

${project.slug === "cloud-nexus-pilot" ? "- Landing page\n- Auth pages\n- Dashboard shell\n- Transcript upload page\n- AI summary placeholder\n- Prompt library page\n- Pricing page" : ""}
${project.slug === "devops-automation-agency" ? "- Landing page\n- Services page\n- Case studies page\n- Contact page\n- Lead form page\n- Booking placeholder" : ""}
${project.slug === "cloud-security-digital-factory" ? "- Landing page\n- Catalog page\n- Product detail page template\n- Downloads placeholder\n- Contact page\n- Pricing and bundles page" : ""}
${project.slug === "ai-automation-agency" ? "- Landing page\n- Offers page\n- Intake form page\n- Case studies page\n- Proposal request page\n- Contact page" : ""}
${project.slug === "cloud-nexus-market" ? "- Homepage\n- Categories page\n- Product listing page\n- Product detail page template\n- Digital downloads page\n- Contact page" : ""}

## Docs

- \`docs/PRD.md\`
- \`docs/ROADMAP.md\`
- \`docs/TASKS.md\`
`;
}

function prd(project) {
  return `# Product Requirements Document

## Product

${project.name}

## Purpose

${project.tagline}

## MVP Goals

${project.description}

## Primary User Outcomes

- Understand the offer within the first screenful.
- Navigate to the most important conversion pages quickly.
- Trust the product because the UI feels modern, polished, and intentional.

## MVP Scope

${project.slug === "cloud-nexus-pilot" ? "- Marketing site\n- Auth entry points\n- Dashboard shell\n- Transcript upload flow placeholder\n- AI summary placeholder\n- Prompt library\n- Pricing" : ""}
${project.slug === "devops-automation-agency" ? "- Marketing site\n- Services overview\n- Case studies\n- Contact and lead capture flows\n- Booking placeholder" : ""}
${project.slug === "cloud-security-digital-factory" ? "- Product merchandising homepage\n- Catalog grid\n- Dynamic product detail template\n- Downloads area placeholder\n- Contact flow\n- Bundle pricing" : ""}
${project.slug === "ai-automation-agency" ? "- Marketing site\n- Offer packaging\n- Intake flow\n- Case studies\n- Proposal request\n- Contact flow" : ""}
${project.slug === "cloud-nexus-market" ? "- Market homepage\n- Categories overview\n- Product listing\n- Dynamic product detail template\n- Downloads area\n- Contact flow" : ""}

## Non-Goals For MVP

- Payment processing
- Real authentication and user provisioning unless separately integrated
- Production analytics and CRM wiring
- Full CMS authoring

## Technical Notes

- App Router structure keeps marketing and product pages organized.
- Tailwind CSS is used for consistent, reusable UI patterns.
- Manual integration items are tracked in \`docs/TASKS.md\`.
`;
}

function roadmap(project) {
  return `# Roadmap

## Phase 1

- Finalize messaging, visuals, and conversion copy.
- Connect forms to a real backend or CRM.
- Add analytics and SEO metadata refinements.

## Phase 2

${project.slug === "cloud-nexus-pilot" ? "- Implement auth and workspace persistence\n- Add transcript ingestion and storage\n- Add real AI summarization pipelines" : ""}
${project.slug === "devops-automation-agency" ? "- Add CMS-backed case studies and service content\n- Embed booking provider\n- Add lead scoring and automated follow-up" : ""}
${project.slug === "cloud-security-digital-factory" ? "- Add checkout and digital asset delivery\n- Add licensing and update notifications\n- Add search and filters to the catalog" : ""}
${project.slug === "ai-automation-agency" ? "- Add proposal generation workflows\n- Integrate intake forms with automation pipelines\n- Publish validated case studies" : ""}
${project.slug === "cloud-nexus-market" ? "- Add cart and checkout flows\n- Add customer accounts and downloads history\n- Add merchandising filters and featured collections" : ""}

## Phase 3

- Add observability, error tracking, and performance budgets.
- Add a CMS or structured content system for ongoing updates.
- Prepare deployment automation in \`.github/workflows/deploy.yml\`.
`;
}

function tasks(project) {
  return `# Tasks

## Manual Input Needed

${project.tasks.map((task) => `- ${task}`).join("\n")}

## Recommended Next Steps

- Run \`npm install\`
- Create \`.env.local\` from \`.env.example\`
- Decide on hosting, domains, and deployment secrets
- Configure the deployment workflow once the hosting target is chosen
`;
}

function homePage() {
  return `import Link from "next/link";
import { ContentGrid } from "@/components/content-grid";
import { siteConfig } from "@/lib/site";

export default function HomePage() {
  return (
    <>
      <section className="section-shell py-16 lg:py-24">
        <div className="grid gap-12 lg:grid-cols-[1.2fr_0.8fr] lg:items-center">
          <div>
            <span className="pill">{siteConfig.home.eyebrow}</span>
            <h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-tight text-slate-950 lg:text-7xl">
              {siteConfig.home.title}
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{siteConfig.home.description}</p>
            <div className="mt-8 flex flex-wrap gap-4">
              <Link href={siteConfig.cta.href} className="rounded-full bg-slate-950 px-6 py-3 text-sm font-semibold text-white">
                {siteConfig.cta.label}
              </Link>
              <Link href={siteConfig.mainNav[0].href} className="rounded-full border border-slate-300 bg-white px-6 py-3 text-sm font-semibold text-slate-700">
                Explore
              </Link>
            </div>
          </div>
          <div className="panel p-8">
            <div className="grid gap-4">
              {siteConfig.home.stats.map((item) => (
                <div key={item.title} className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
                  <p className="text-sm font-semibold text-primary">{item.meta}</p>
                  <h2 className="mt-2 text-xl font-semibold text-slate-950">{item.title}</h2>
                  <p className="mt-2 text-sm leading-7 text-slate-600">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="section-shell pb-16">
        <div className="mb-8">
          <span className="pill">Why this starter works</span>
          <h2 className="mt-4 text-3xl font-semibold text-slate-950">Reusable patterns with room to scale.</h2>
        </div>
        <ContentGrid items={siteConfig.home.highlights} />
      </section>
    </>
  );
}
`;
}

function simpleGridPage(pageKey) {
  return `import { ContentGrid } from "@/components/content-grid";
import { PageHero } from "@/components/page-hero";
import { siteConfig } from "@/lib/site";

export default function ${pascal(pageKey)}Page() {
  const page = siteConfig.pages.${pageKey};

  return (
    <>
      <PageHero eyebrow={page.eyebrow} title={page.title} description={page.description} />
      <section className="section-shell pb-16">
        <ContentGrid items={page.items} />
      </section>
    </>
  );
}
`;
}

function contactPage(title, description, submitLabel, context) {
  return `import { ContactForm } from "@/components/contact-form";
import { PageHero } from "@/components/page-hero";

export default function ContactPage() {
  return (
    <>
      <PageHero eyebrow="Contact" title="${title}" description="${description}" />
      <section className="section-shell grid gap-8 pb-16 lg:grid-cols-[1fr_320px]">
        <ContactForm submitLabel="${submitLabel}" context="${context}" />
        <aside className="panel p-8">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Next step</p>
          <h2 className="mt-3 text-2xl font-semibold text-slate-950">We reply with a clear recommended path.</h2>
          <p className="mt-4 text-sm leading-7 text-slate-600">
            Use this space for response times, a sales inbox, booking links, or trust signals once the live workflow is chosen.
          </p>
        </aside>
      </section>
    </>
  );
}
`;
}

function cloudNexusPilotFiles(project) {
  return {
    "app/page.tsx": homePage(),
    "app/auth/login/page.tsx": `export default function LoginPage() {
  return (
    <section className="section-shell flex min-h-[70vh] items-center justify-center py-16">
      <div className="panel w-full max-w-md p-8">
        <span className="pill">Welcome back</span>
        <h1 className="mt-6 text-3xl font-semibold text-slate-950">Sign in to your workspace.</h1>
        <p className="mt-3 text-sm leading-7 text-slate-600">Connect your real auth provider later. This page is ready for UI integration.</p>
        <div className="mt-8 space-y-4">
          <input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Email" />
          <input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Password" type="password" />
          <button className="w-full rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Sign in</button>
        </div>
      </div>
    </section>
  );
}
`,
    "app/auth/signup/page.tsx": `export default function SignupPage() {
  return (
    <section className="section-shell flex min-h-[70vh] items-center justify-center py-16">
      <div className="panel w-full max-w-md p-8">
        <span className="pill">Create account</span>
        <h1 className="mt-6 text-3xl font-semibold text-slate-950">Start your first AI copilot workspace.</h1>
        <p className="mt-3 text-sm leading-7 text-slate-600">Swap these inputs for real auth wiring when your provider is selected.</p>
        <div className="mt-8 space-y-4">
          <input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Full name" />
          <input className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Work email" />
          <button className="w-full rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Create workspace</button>
        </div>
      </div>
    </section>
  );
}
`,
    "app/dashboard/page.tsx": `import { AppShell } from "@/components/app-shell";

const nav = [
  { label: "Overview", href: "/dashboard" },
  { label: "Transcripts", href: "/transcripts" },
  { label: "Prompt Library", href: "/prompt-library" },
  { label: "Pricing", href: "/pricing" },
];

export default function DashboardPage() {
  return (
    <AppShell
      title="Workspace Overview"
      description="A clean dashboard shell ready for metrics, workspace settings, billing, and recent activity."
      nav={nav}
    >
      <div className="grid gap-6 md:grid-cols-3">
        {[
          ["Uploads this week", "18"],
          ["Saved prompt sets", "12"],
          ["Pending summaries", "4"],
        ].map(([label, value]) => (
          <div key={label} className="panel p-6">
            <p className="text-sm text-slate-500">{label}</p>
            <p className="mt-3 text-4xl font-semibold text-slate-950">{value}</p>
          </div>
        ))}
      </div>
      <div className="panel p-8">
        <h2 className="text-2xl font-semibold text-slate-950">Recent activity</h2>
        <div className="mt-6 space-y-4">
          {[
            "Interview debrief prompt updated for growth roles",
            "Candidate call transcript uploaded and queued",
            "Weekly stakeholder summary template published",
          ].map((item) => (
            <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4 text-sm text-slate-700">
              {item}
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
`,
    "app/transcripts/page.tsx": `import { AppShell } from "@/components/app-shell";

const nav = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Upload Queue", href: "/transcripts" },
  { label: "AI Summary", href: "/summary" },
  { label: "Prompt Library", href: "/prompt-library" },
];

export default function TranscriptsPage() {
  return (
    <AppShell
      title="Transcript Uploads"
      description="Prepare the upload area for audio, transcript files, or meeting note imports."
      nav={nav}
    >
      <div className="panel p-8">
        <h2 className="text-2xl font-semibold text-slate-950">Upload transcript</h2>
        <p className="mt-3 text-sm leading-7 text-slate-600">
          Replace this placeholder with your storage integration, validation flow, and processing queue.
        </p>
        <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-slate-50 px-6 py-14 text-center text-sm text-slate-500">
          Drag transcripts here or connect a recorder pipeline.
        </div>
      </div>
      <div className="panel p-8">
        <h2 className="text-2xl font-semibold text-slate-950">Recent uploads</h2>
        <div className="mt-6 space-y-3">
          {[
            "Engineering manager interview - March panel",
            "Customer discovery call - enterprise prospect",
            "Weekly hiring sync - product and design",
          ].map((item) => (
            <div key={item} className="rounded-2xl border border-slate-200 px-4 py-4 text-sm text-slate-700">
              {item}
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
`,
    "app/summary/page.tsx": `import Link from "next/link";
import { PageHero } from "@/components/page-hero";

export default function SummaryPage() {
  return (
    <>
      <PageHero
        eyebrow="AI Summary"
        title="Summary workflows are staged and ready for your model pipeline."
        description="This placeholder page marks the handoff point for transcript parsing, prompt orchestration, and response rendering."
      />
      <section className="section-shell pb-16">
        <div className="panel p-8">
          <h2 className="text-2xl font-semibold text-slate-950">Suggested next implementation steps</h2>
          <div className="mt-6 grid gap-4 md:grid-cols-3">
            {[
              "Choose a summarization model and system prompt versioning strategy.",
              "Add transcript chunking, redaction, and retry logic.",
              "Persist structured outputs for recruiter, operator, or stakeholder views.",
            ].map((item) => (
              <div key={item} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7 text-slate-700">
                {item}
              </div>
            ))}
          </div>
          <Link href="/prompt-library" className="mt-8 inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">
            Review prompt library
          </Link>
        </div>
      </section>
    </>
  );
}
`,
    "app/prompt-library/page.tsx": simpleGridPage("promptLibrary"),
    "app/pricing/page.tsx": simpleGridPage("pricing"),
  };
}

function devopsAgencyFiles() {
  return {
    "app/page.tsx": homePage(),
    "app/services/page.tsx": simpleGridPage("services"),
    "app/case-studies/page.tsx": simpleGridPage("caseStudies"),
    "app/contact/page.tsx": contactPage(
      "Talk through your platform, security, or automation roadmap.",
      "Use this page to start consulting conversations with engineering leaders, founders, and operations teams.",
      "Send inquiry",
      "We need help modernizing CI/CD, security controls, and AWS delivery workflows."
    ),
    "app/lead-form/page.tsx": `import { ContactForm } from "@/components/contact-form";
import { PageHero } from "@/components/page-hero";

export default function LeadFormPage() {
  return (
    <>
      <PageHero
        eyebrow="Lead Form"
        title="Qualify the project before the first call."
        description="Capture enough signal to tailor discovery and accelerate the proposal process."
      />
      <section className="section-shell pb-16">
        <ContactForm
          submitLabel="Submit lead"
          context="Current environment, delivery blockers, compliance needs, budget range, and urgency."
        />
      </section>
    </>
  );
}
`,
    "app/booking/page.tsx": `import { PageHero } from "@/components/page-hero";

export default function BookingPage() {
  return (
    <>
      <PageHero
        eyebrow="Booking"
        title="A scheduling integration will live here."
        description="Wire this route to Calendly, Cal.com, or a custom booking flow once the sales process is finalized."
      />
      <section className="section-shell pb-16">
        <div className="panel p-8 text-sm leading-7 text-slate-600">
          This placeholder is intentionally lightweight so you can add the provider embed or API flow that fits your consulting process.
        </div>
      </section>
    </>
  );
}
`,
  };
}

function digitalFactoryFiles() {
  return {
    "app/page.tsx": homePage(),
    "app/catalog/page.tsx": `import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { siteConfig } from "@/lib/site";

export default function CatalogPage() {
  return (
    <>
      <PageHero
        eyebrow="Catalog"
        title="Browse digital assets built for cloud and security operators."
        description="Merchandise templates, SOPs, and documentation kits in a format that feels operational, not generic."
      />
      <section className="section-shell pb-16">
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {siteConfig.products.map((product) => (
            <article key={product.slug} className="panel p-6">
              <p className="text-sm font-semibold text-primary">{product.format}</p>
              <h2 className="mt-3 text-2xl font-semibold text-slate-950">{product.name}</h2>
              <p className="mt-3 text-sm leading-7 text-slate-600">{product.summary}</p>
              <div className="mt-6 flex items-center justify-between">
                <span className="text-lg font-semibold text-slate-950">{product.price}</span>
                <Link href={\`/products/\${product.slug}\`} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">
                  View
                </Link>
              </div>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}
`,
    "app/products/[slug]/page.tsx": `import { notFound } from "next/navigation";
import { siteConfig } from "@/lib/site";

type ProductDetailPageProps = {
  params: Promise<{ slug: string }>;
};

export default async function ProductDetailPage({ params }: ProductDetailPageProps) {
  const { slug } = await params;
  const product = siteConfig.products.find((item) => item.slug === slug);

  if (!product) {
    notFound();
  }

  return (
    <section className="section-shell py-16">
      <div className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr]">
        <div className="panel p-8">
          <span className="pill">{product.format}</span>
          <h1 className="mt-6 text-4xl font-semibold text-slate-950">{product.name}</h1>
          <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">{product.summary}</p>
          <div className="mt-8 grid gap-4 md:grid-cols-2">
            {[
              "Implementation notes",
              "Suggested use cases",
              "Update policy",
              "License terms",
            ].map((item) => (
              <div key={item} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                {item}
              </div>
            ))}
          </div>
        </div>
        <aside className="panel p-8">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Price</p>
          <p className="mt-3 text-4xl font-semibold text-slate-950">{product.price}</p>
          <p className="mt-4 text-sm leading-7 text-slate-600">
            Connect this panel to your checkout and digital delivery workflow when you are ready to sell live inventory.
          </p>
          <button className="mt-8 w-full rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">
            Checkout coming soon
          </button>
        </aside>
      </div>
    </section>
  );
}
`,
    "app/downloads/page.tsx": `import { PageHero } from "@/components/page-hero";

export default function DownloadsPage() {
  return (
    <>
      <PageHero
        eyebrow="Downloads"
        title="Customer downloads and update delivery will live here."
        description="Keep this route reserved for signed-in delivery, receipts, product updates, and access management."
      />
      <section className="section-shell pb-16">
        <div className="panel p-8">
          <div className="grid gap-4 md:grid-cols-3">
            {[
              "Recent purchases",
              "Version history",
              "License details",
            ].map((item) => (
              <div key={item} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
`,
    "app/contact/page.tsx": contactPage(
      "Request a custom bundle or ask about enterprise usage.",
      "This contact route is ready for licensing inquiries, bundle questions, and advisory upsells.",
      "Send request",
      "We need a custom documentation or playbook bundle for our team."
    ),
    "app/pricing/page.tsx": simpleGridPage("pricing"),
  };
}

function automationAgencyFiles() {
  return {
    "app/page.tsx": homePage(),
    "app/offers/page.tsx": simpleGridPage("offers"),
    "app/case-studies/page.tsx": simpleGridPage("caseStudies"),
    "app/intake/page.tsx": `import { ContactForm } from "@/components/contact-form";
import { PageHero } from "@/components/page-hero";

export default function IntakePage() {
  return (
    <>
      <PageHero
        eyebrow="Intake"
        title="Collect the operational context before you scope the build."
        description="Use this form page to gather systems involved, human review requirements, and automation goals."
      />
      <section className="section-shell pb-16">
        <ContactForm
          submitLabel="Submit intake"
          context="Key workflows, systems to integrate, team members involved, failure risks, and desired outcomes."
        />
      </section>
    </>
  );
}
`,
    "app/proposal-request/page.tsx": `import { ContactForm } from "@/components/contact-form";
import { PageHero } from "@/components/page-hero";

export default function ProposalRequestPage() {
  return (
    <>
      <PageHero
        eyebrow="Proposal Request"
        title="Start a proposal request with enough detail to move fast."
        description="This route is designed for buyers who are past browsing and ready to discuss scope and delivery."
      />
      <section className="section-shell pb-16">
        <ContactForm
          submitLabel="Request proposal"
          context="Business problem, current process, expected ROI, timeline, stakeholders, and procurement needs."
        />
      </section>
    </>
  );
}
`,
    "app/contact/page.tsx": contactPage(
      "Start the conversation about your automation roadmap.",
      "Use this route for general inquiries, partnerships, or project conversations that need a lighter entry point.",
      "Send message",
      "We want to explore AI workflow automation for our internal operations."
    ),
  };
}

function marketFiles() {
  return {
    "app/page.tsx": homePage(),
    "app/categories/page.tsx": `import { ContentGrid } from "@/components/content-grid";
import { PageHero } from "@/components/page-hero";
import { siteConfig } from "@/lib/site";

export default function CategoriesPage() {
  return (
    <>
      <PageHero
        eyebrow="Categories"
        title="Explore the storefront by product family."
        description="Category navigation keeps the market organized as the catalog grows."
      />
      <section className="section-shell pb-16">
        <ContentGrid items={siteConfig.categories} />
      </section>
    </>
  );
}
`,
    "app/products/page.tsx": `import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { siteConfig } from "@/lib/site";

export default function ProductsPage() {
  return (
    <>
      <PageHero
        eyebrow="Products"
        title="A clean product listing page for digital cloud inventory."
        description="Add filters, reviews, badges, and checkout wiring over time without reworking the foundation."
      />
      <section className="section-shell pb-16">
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {siteConfig.products.map((product) => (
            <article key={product.slug} className="panel p-6">
              <p className="text-sm font-semibold text-primary">{product.format}</p>
              <h2 className="mt-3 text-2xl font-semibold text-slate-950">{product.name}</h2>
              <p className="mt-3 text-sm leading-7 text-slate-600">{product.summary}</p>
              <div className="mt-6 flex items-center justify-between">
                <span className="text-lg font-semibold text-slate-950">{product.price}</span>
                <Link href={\`/products/\${product.slug}\`} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">
                  View
                </Link>
              </div>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}
`,
    "app/products/[slug]/page.tsx": `import { notFound } from "next/navigation";
import { siteConfig } from "@/lib/site";

type ProductDetailPageProps = {
  params: Promise<{ slug: string }>;
};

export default async function ProductDetailPage({ params }: ProductDetailPageProps) {
  const { slug } = await params;
  const product = siteConfig.products.find((item) => item.slug === slug);

  if (!product) {
    notFound();
  }

  return (
    <section className="section-shell py-16">
      <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="panel p-8">
          <span className="pill">{product.format}</span>
          <h1 className="mt-6 text-4xl font-semibold text-slate-950">{product.name}</h1>
          <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">{product.summary}</p>
          <div className="mt-8 grid gap-4 md:grid-cols-2">
            {[
              "Product overview",
              "What is included",
              "Suggested buyer profile",
              "Future add-ons",
            ].map((item) => (
              <div key={item} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                {item}
              </div>
            ))}
          </div>
        </div>
        <aside className="panel p-8">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Price</p>
          <p className="mt-3 text-4xl font-semibold text-slate-950">{product.price}</p>
          <p className="mt-4 text-sm leading-7 text-slate-600">
            Connect this area to your checkout provider, customer account flow, and order tracking when ready.
          </p>
          <button className="mt-8 w-full rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white">
            Buy flow coming soon
          </button>
        </aside>
      </div>
    </section>
  );
}
`,
    "app/downloads/page.tsx": `import { PageHero } from "@/components/page-hero";

export default function DownloadsPage() {
  return (
    <>
      <PageHero
        eyebrow="Downloads"
        title="Reserve this area for customer download access."
        description="As checkout and accounts are added, this route can become the post-purchase delivery center."
      />
      <section className="section-shell pb-16">
        <div className="panel p-8">
          <div className="grid gap-4 md:grid-cols-3">
            {[
              "Order history",
              "License access",
              "Download queue",
            ].map((item) => (
              <div key={item} className="rounded-3xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-700">
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
`,
    "app/contact/page.tsx": contactPage(
      "Ask about products, bundles, or partner opportunities.",
      "Use this route for general market support, bundle requests, or implementation service inquiries.",
      "Send message",
      "We need help choosing the right templates and bundles for our cloud team."
    ),
  };
}

function pascal(value) {
  return value
    .replace(/(^\w|-\w|_\w)/g, (match) => match.replace(/[-_]/g, "").toUpperCase());
}

for (const project of projects) {
  const projectRoot = path.join(root, project.slug);
  const siteConfig = {
    name: project.name,
    brandMark: project.brandMark,
    tagline: project.tagline,
    description: project.description,
    footer: project.footer,
    cta: project.cta,
    mainNav: project.mainNav,
    home: project.home,
    pages: project.pages ?? {},
    products: project.products ?? [],
    categories: project.categories ?? [],
  };

  for (const [relativePath, content] of Object.entries(commonFiles)) {
    writeFile(projectRoot, relativePath, content);
  }

  writeFile(projectRoot, "package.json", packageJson(project));
  writeFile(projectRoot, "README.md", readme(project));
  writeFile(projectRoot, "docs/PRD.md", prd(project));
  writeFile(projectRoot, "docs/ROADMAP.md", roadmap(project));
  writeFile(projectRoot, "docs/TASKS.md", tasks(project));
  writeFile(projectRoot, "lib/site.ts", toTsExport(siteConfig));

  let repoFiles = {};

  if (project.slug === "cloud-nexus-pilot") {
    repoFiles = cloudNexusPilotFiles(project);
  } else if (project.slug === "devops-automation-agency") {
    repoFiles = devopsAgencyFiles(project);
  } else if (project.slug === "cloud-security-digital-factory") {
    repoFiles = digitalFactoryFiles(project);
  } else if (project.slug === "ai-automation-agency") {
    repoFiles = automationAgencyFiles(project);
  } else if (project.slug === "cloud-nexus-market") {
    repoFiles = marketFiles(project);
  }

  for (const [relativePath, content] of Object.entries(repoFiles)) {
    writeFile(projectRoot, relativePath, content);
  }
}
